Insert into tb_estado (id, nome, sigla) values
(1, 'Acre', 'AC'),
(2, 'Alagoas', 'AL'),
(3, 'Amazonas', 'AM'),
(4, 'Amapá', 'AP'),
(5, 'Bahia', 'BA'),
(6, 'Ceará', 'CE'),
(7, 'Distrito Federal', 'DF'),
(8, 'Espírito Santo', 'ES'),
(9, 'Goiás', 'GO'),
(10, 'Maranhão', 'MA'),
(11, 'Minas Gerais', 'MG'),
(12, 'Mato Grosso do Sul', 'MS'),
(13, 'Mato Grosso', 'MT'),
(14, 'Pará', 'PA'),
(15, 'Paraíba', 'PB'),
(16, 'Pernambuco', 'PE'),
(17, 'Piauí', 'PI'),
(18, 'Paraná', 'PR'),
(19, 'Rio de Janeiro', 'RJ'),
(20, 'Rio Grande do Norte', 'RN'),
(21, 'Rondônia', 'RO'),
(22, 'Roraima', 'RR'),
(23, 'Rio Grande do Sul', 'RS'),
(24, 'Santa Catarina', 'SC'),
(25, 'Sergipe', 'SE'),
(26, 'São Paulo', 'SP'),
(27, 'Tocantins', 'TO');

INSERT INTO tb_cidade (nome,estado_id) VALUES
('Abatiá', 18),
('Adrianópolis', 18),
('Agudos do Sul', 18),
('Almirante Tamandaré', 18),
('Altamira do Paraná', 18),
('Alto Paraíso', 18),
('Alto Paraná', 18),
('Alto Piquiri', 18),
('Altônia', 18),
('Alvorada do Sul', 18),
('Amaporã', 18),
('Ampére', 18),
('Anahy', 18),
('Andirá', 18),
('Ângulo', 18),
('Antonina', 18),
('Antônio Olinto', 18),
('Apucarana', 18),
('Arapongas', 18),
('Arapoti', 18),
('Arapuã', 18),
('Araruna', 18),
('Araucária', 18),
('Ariranha do Ivaí', 18),
('Assaí', 18),
('Assis Chateaubriand' ,18),
('Astorga', 18),
('Atalaia', 18),
('Balsa Nova', 18),
('Bandeirantes', 18),
('Barbosa Ferraz', 18),
('Barra do Jacaré', 18),
('Barracão', 18),
('Bela Vista da Caroba', 18),
('Bela Vista do Paraíso', 18),
('Bituruna', 18),
('Boa Esperança', 18),
('Boa Esperança do Iguaçu', 18),
('Boa Ventura de São Roque', 18),
('Boa Vista da Aparecida', 18),
('Bocaiúva do Sul', 18),
('Bom Jesus do Sul', 18),
('Bom Sucesso', 18),
('Bom Sucesso do Sul', 18),
('Borrazópolis', 18),
('Braganey', 18),
('Brasilândia do Sul', 18),
('Cafeara', 18),
('Cafelândia', 18),
('Cafezal do Sul', 18),
('Califórnia', 18),
('Cambará', 18),
('Cambé', 18),
('Cambira', 18),
('Campina da Lagoa', 18),
('Campina do Simão', 18),
('Campina Grande do Sul', 18),
('Campo Bonito', 18),
('Campo do Tenente', 18),
('Campo Largo', 18),
('Campo Magro', 18),
('Campo Mourão', 18),
('Cândido de Abreu', 18),
('Candói', 18),
('Cantagalo', 18),
('Capanema', 18),
('Capitão Leônidas Marques', 18),
('Carambeí', 18),
('Carlópolis', 18),
('Cascavel', 18),
('Castro', 18),
('Catanduvas', 18),
('Centenário do Sul', 18),
('Cerro Azul', 18),
('Céu Azul', 18),
('Chopinzinho', 18),
('Cianorte', 18),
('Cidade Gaúcha', 18),
('Clevelândia', 18),
('Colombo', 18),
('Colorado', 18),
('Congonhinhas', 18),
('Conselheiro Mairinck', 18),
('Contenda', 18),
('Corbélia', 18),
('Cornélio Procópio', 18),
('Coronel Domingos Soares', 18),
('Coronel Vivida', 18),
('Corumbataí do Sul', 18),
('Cruz Machado', 18),
('Cruzeiro do Iguaçu', 18),
('Cruzeiro do Oeste', 18),
('Cruzeiro do Sul', 18),
('Cruzmaltina', 18),
('Curitiba', 18),
('Curiúva', 18),
('Diamante do Norte', 18),
('Diamante do Sul', 18),
('Diamante D Oeste', 18);