Insert into tb_estado (id, nome, sigla) values
(1, 'Acre', 'AC'),
(2, 'Alagoas', 'AL'),
(3, 'Amazonas', 'AM'),
(4, 'Amapá', 'AP'),
(5, 'Bahia', 'BA'),
(6, 'Ceará', 'CE'),
(7, 'Distrito Federal', 'DF'),
(8, 'Espírito Santo', 'ES'),
(9, 'Goiás', 'GO'),
(10, 'Maranhão', 'MA'),
(11, 'Minas Gerais', 'MG'),
(12, 'Mato Grosso do Sul', 'MS'),
(13, 'Mato Grosso', 'MT'),
(14, 'Pará', 'PA'),
(15, 'Paraíba', 'PB'),
(16, 'Pernambuco', 'PE'),
(17, 'Piauí', 'PI'),
(18, 'Paraná', 'PR'),
(19, 'Rio de Janeiro', 'RJ'),
(20, 'Rio Grande do Norte', 'RN'),
(21, 'Rondônia', 'RO'),
(22, 'Roraima', 'RR'),
(23, 'Rio Grande do Sul', 'RS'),
(24, 'Santa Catarina', 'SC'),
(25, 'Sergipe', 'SE'),
(26, 'São Paulo', 'SP'),
(27, 'Tocantins', 'TO');

INSERT INTO tb_cidade (nome,estado_id) VALUES
('Abatiá', 18),
('Adrianópolis', 18),
('Agudos do Sul', 18),
('Almirante Tamandaré', 18),
('Altamira do Paraná', 18),
('Alto Paraíso', 18),
('Alto Paraná', 18),
('Alto Piquiri', 18),
('Altônia', 18),
('Alvorada do Sul', 18),
('Amaporã', 18),
('Ampére', 18),
('Anahy', 18),
('Andirá', 18),
('Ângulo', 18),
('Antonina', 18),
('Antônio Olinto', 18),
('Apucarana', 18),
('Arapongas', 18),
('Arapoti', 18),
('Arapuã', 18),
('Araruna', 18),
('Araucária', 18),
('Ariranha do Ivaí', 18),
('Assaí', 18),
('Assis Chateaubriand' ,18),
('Astorga', 18),
('Atalaia', 18),
('Balsa Nova', 18),
('Bandeirantes', 18),
('Barbosa Ferraz', 18),
('Barra do Jacaré', 18),
('Barracão', 18),
('Bela Vista da Caroba', 18),
('Bela Vista do Paraíso', 18),
('Bituruna', 18),
('Boa Esperança', 18),
('Boa Esperança do Iguaçu', 18),
('Boa Ventura de São Roque', 18),
('Boa Vista da Aparecida', 18),
('Bocaiúva do Sul', 18),
('Bom Jesus do Sul', 18),
('Bom Sucesso', 18),
('Bom Sucesso do Sul', 18),
('Borrazópolis', 18),
('Braganey', 18),
('Brasilândia do Sul', 18),
('Cafeara', 18),
('Cafelândia', 18),
('Cafezal do Sul', 18),
('Califórnia', 18),
('Cambará', 18),
('Cambé', 18),
('Cambira', 18),
('Campina da Lagoa', 18),
('Campina do Simão', 18),
('Campina Grande do Sul', 18),
('Campo Bonito', 18),
('Campo do Tenente', 18),
('Campo Largo', 18),
('Campo Magro', 18),
('Campo Mourão', 18),
('Cândido de Abreu', 18),
('Candói', 18),
('Cantagalo', 18),
('Capanema', 18),
('Capitão Leônidas Marques', 18),
('Carambeí', 18),
('Carlópolis', 18),
('Cascavel', 18),
('Castro', 18),
('Catanduvas', 18),
('Centenário do Sul', 18),
('Cerro Azul', 18),
('Céu Azul', 18),
('Chopinzinho', 18),
('Cianorte', 18),
('Cidade Gaúcha', 18),
('Clevelândia', 18),
('Colombo', 18),
('Colorado', 18),
('Congonhinhas', 18),
('Conselheiro Mairinck', 18),
('Contenda', 18),
('Corbélia', 18),
('Cornélio Procópio', 18),
('Coronel Domingos Soares', 18),
('Coronel Vivida', 18),
('Corumbataí do Sul', 18),
('Cruz Machado', 18),
('Cruzeiro do Iguaçu', 18),
('Cruzeiro do Oeste', 18),
('Cruzeiro do Sul', 18),
('Cruzmaltina', 18),
('Curitiba', 18),
('Curiúva', 18),
('Diamante do Norte', 18),
('Diamante do Sul', 18),
('Diamante D Oeste', 18),
('Dois Vizinhos', 18),
('Douradina', 18),
('Doutor Camargo', 18),
('Doutor Ulysses', 18),
('Enéas Marques', 18),
('Engenheiro Beltrão', 18),
('Entre Rios do Oeste', 18),
('Esperança Nova', 18),
('Espigão Alto do Iguaçu', 18),
('Farol', 18),
('Faxinal', 18),
('Fazenda Rio Grande', 18),
('Fênix', 18),
('Fernandes Pinheiro', 18),
('Figueira', 18),
('Flor da Serra do Sul', 18),
('Floraí', 18),
('Floresta', 18),
('Florestópolis', 18),
('Flórida', 18),
('Formosa do Oeste', 18),
('Foz do Iguaçu', 18),
('Foz do Jordão', 18),
('Francisco Alves', 18),
('Francisco Beltrão', 18),
('General Carneiro', 18),
('Godoy Moreira', 18),
('Goioerê', 18),
('Goioxim', 18),
('Grandes Rios', 18),
('Guaíra', 18),
('Guairaçá', 18),
('Guamiranga', 18),
('Guapirama', 18),
('Guaporema', 18),
('Guaraci', 18),
('Guaraniaçu', 18),
('Guarapuava', 18),
('Guaraqueçaba', 18),
('Guaratuba', 18),
('Honório Serpa', 18),
('Ibaiti', 18),
('Ibema', 18),
('Ibiporã', 18),
('Icaraíma', 18),
('Iguaraçu', 18),
('Iguatu', 18),
('Imbaú', 18),
('Imbituva', 18),
('Inácio Martins', 18),
('Inajá', 18),
('Indianópolis', 18),
('Ipiranga', 18),
('Iporã', 18),
('Iracema do Oeste', 18),
('Irati', 18),
('Iretama', 18),
('Itaguajé', 18),
('Itaipulândia', 18),
('Itambaracá', 18),
('Itambé', 18),
('Itapejara d Oeste', 18),
('Itaperuçu', 18),
('Itaúna do Sul', 18),
('Ivaí', 18),
('Ivaiporã', 18),
('Ivaté', 18),
('Ivatuba', 18),
('Jaboti', 18),
('Jacarezinho', 18),
('Jaguapitã', 18),
('Jaguariaíva', 18),
('Jandaia do Sul', 18),
('Janiópolis', 18),
('Japira', 18),
('Japurá', 18),
('Jardim Alegre', 18),
('Jardim Olinda', 18),
('Jataizinho', 18),
('Jesuítas', 18),
('Joaquim Távora', 18),
('Jundiaí do Sul', 18),
('Juranda', 18),
('Jussara', 18),
('Kaloré', 18),
('Lapa', 18),
('Laranjal', 18),
('Laranjeiras do Sul', 18),
('Leópolis', 18),
('Lidianópolis', 18),
('Lindoeste', 18),
('Loanda', 18),
('Lobato', 18),
('Londrina', 18),
('Luiziana', 18),
('Lunardelli', 18),
('Lupionópolis', 18),
('Mallet', 18),
('Mamborê', 18),
('Mandaguaçu', 18),
('Mandaguari', 18),
('Mandirituba', 18),
('Manfrinópolis', 18),
('Mangueirinha', 18),
('Manoel Ribas', 18),
('Marechal Cândido Rondon', 18),
('Maria Helena', 18),
('Marialva', 18),
('Marilândia do Sul', 18),
('Marilena', 18),
('Mariluz', 18),
('Maringá', 18),
('Mariópolis', 18),
('Maripá', 18),
('Marmeleiro', 18),
('Marquinho', 18),
('Marumbi', 18),
('Matelândia', 18),
('Matinhos', 18),
('Mato Rico', 18),
('Mauá da Serra', 18),
('Medianeira', 18),
('Mercedes', 18),
('Mirador', 18),
('Miraselva', 18),
('Missal', 18),
('Moreira Sales', 18),
('Morretes', 18),
('Munhoz de Melo', 18),
('Nossa Senhora das Graças', 18),
('Nova Aliança do Ivaí', 18),
('Nova América da Colina', 18),
('Nova Aurora', 18),
('Nova Cantu', 18),
('Nova Esperança', 18),
('Nova Esperança do Sudoeste', 18),
('Nova Fátima', 18),
('Nova Laranjeiras', 18),
('Nova Londrina', 18),
('Nova Olímpia', 18),
('Nova Prata do Iguaçu', 18),
('Nova Santa Bárbara', 18),
('Nova Santa Rosa', 18),
('Nova Tebas', 18),
('Novo Itacolomi', 18),
('Ortigueira', 18),
('Ourizona', 18),
('Ouro Verde do Oeste', 18),
('Paiçandu', 18),
('Palmas', 18),
('Palmeira', 18),
('Palmital', 18),
('Palotina', 18),
('Paraíso do Norte', 18),
('Paranacity', 18),
('Paranaguá', 18),
('Paranapoema', 18),
('Paranavaí', 18),
('Pato Bragado', 18),
('Pato Branco', 18),
('Paula Freitas', 18),
('Paulo Frontin', 18),
('Peabiru', 18),
('Perobal', 18),
('Pérola', 18),
('Pérola d Oeste', 18),
('Piên', 18),
('Pinhais', 18),
('Pinhal de São Bento', 18),
('Pinhalão', 18),
('Pinhão', 18),
('Piraí do Sul', 18),
('Piraquara', 18),
('Pitanga', 18),
('Pitangueiras', 18),
('Planaltina do Paraná', 18),
('Planalto', 18),
('Ponta Grossa', 18),
('Pontal do Paraná', 18),
('Porecatu', 18),
('Porto Amazonas', 18),
('Porto Barreiro', 18),
('Porto Rico', 18),
('Porto Vitória', 18),
('Prado Ferreira', 18),
('Pranchita', 18),
('Presidente Castelo Branco', 18),
('Primeiro de Maio', 18),
('Prudentópolis', 18),
('Quarto Centenário', 18),
('Quatiguá', 18),
('Quatro Barras', 18),
('Quatro Pontes', 18),
('Quedas do Iguaçu', 18),
('Querência do Norte', 18),
('Quinta do Sol', 18),
('Quitandinha', 18),
('Ramilândia', 18),
('Rancho Alegre', 18),
('Rancho Alegre D Oeste', 18),
('Realeza', 18),
('Rebouças', 18),
('Renascença', 18),
('Reserva', 18),
('Reserva do Iguaçu', 18),
('Ribeirão Claro', 18),
('Ribeirão do Pinhal', 18),
('Rio Azul', 18),
('Rio Bom', 18),
('Rio Bonito do Iguaçu', 18),
('Rio Branco do Ivaí', 18),
('Rio Branco do Sul', 18),
('Rio Negro', 18),
('Rolândia', 18),
('Roncador', 18),
('Rondon', 18),
('Rosário do Ivaí', 18),
('Sabáudia', 18),
('Salgado Filho', 18),
('Salto do Itararé', 18),
('Salto do Lontra', 18),
('Santa Amélia', 18),
('Santa Cecília do Pavão', 18),
('Santa Cruz de Monte Castelo', 18),
('Santa Fé', 18),
('Santa Helena', 18),
('Santa Inês', 18),
('Santa Isabel do Ivaí', 18),
('Santa Izabel do Oeste', 18),
('Santa Lúcia', 18),
('Santa Maria do Oeste', 18),
('Santa Mariana', 18),
('Santa Mônica', 18),
('Santa Tereza do Oeste', 18),
('Santa Terezinha de Itaipu', 18),
('Santana do Itararé', 18),
('Santo Antônio da Platina', 18),
('Santo Antônio do Caiuá', 18),
('Santo Antônio do Paraíso', 18),
('Santo Antônio do Sudoeste', 18),
('Santo Inácio', 18),
('São Carlos do Ivaí', 18),
('São Jerônimo da Serra', 18),
('São João', 18),
('São João do Caiuá', 18),
('São João do Ivaí', 18),
('São João do Triunfo', 18),
('São Jorge do Ivaí', 18),
('São Jorge do Patrocínio', 18),
('São Jorge d Oeste', 18),
('São José da Boa Vista', 18),
('São José das Palmeiras', 18),
('São José dos Pinhais', 18),
('São Manoel do Paraná', 18),
('São Mateus do Sul', 18),
('São Miguel do Iguaçu', 18),
('São Pedro do Iguaçu', 18),
('São Pedro do Ivaí', 18),
('São Pedro do Paraná', 18),
('São Sebastião da Amoreira', 18),
('São Tomé', 18),
('Sapopema', 18),
('Sarandi', 18),
('Saudade do Iguaçu', 18),
('Sengés', 18),
('Serranópolis do Iguaçu', 18),
('Sertaneja', 18),
('Sertanópolis', 18),
('Siqueira Campos', 18),
('Sulina', 18),
('Tamarana', 18),
('Tamboara', 18),
('Tapejara', 18),
('Tapira', 18),
('Teixeira Soares', 18),
('Telêmaco Borba', 18),
('Terra Boa', 18),
('Terra Rica', 18),
('Terra Roxa', 18),
('Tibagi', 18),
('Tijucas do Sul', 18),
('Toledo', 18),
('Tomazina', 18),
('Três Barras do Paraná', 18),
('Tunas do Paraná', 18),
('Tuneiras do Oeste', 18),
('Tupãssi', 18),
('Turvo', 18),
('Ubiratã', 18),
('Umuarama', 18),
('União da Vitória', 18),
('Uniflor', 18),
('Uraí', 18),
('Ventania', 18),
('Vera Cruz do Oeste', 18),
('Verê', 18),
('Virmond' ,18),
('Vitorino', 18),
('Wenceslau Braz', 18),
('Xambrê', 18);

INSERT INTO tb_endereco (LOGRADOURO, NUMERO, BAIRRO, COMPLEMENTO, CIDADE_ID) VALUES
('Rua das Flores', 1234, 'Centro', 'Sala 1', 95),
('Rua Florida', 555, 'Parque dos Lagos', 'Casa 2', 95),
('Avenida Brasil', 100, 'Lago Sul', 'Fundos', 95),
('Rua Florida', 555, 'Parque dos Lagos', 'Casa 1', 95),
('Avenida Brasil', 110, 'Lago Sul', null, 95),
('Rua Francisco Juglair', 171, 'Mossunguê', null, 95),
('Rua São Cristovão', 634, 'Guaira', null, 95),
('Rua Vereador Constante Pinto', 328, 'Bacacheri', 'Apto 41', 267),
('Rua José Chaves de Andrade', 1015, 'Pineville', 'Sob. 03', 267);

INSERT INTO tb_diretor_espiritual (NOME, OBSERVACOES, TELEFONE, ENDERECO_ID) VALUES
('Padre Pio Teste', 'Observações testes', '41998765432', 1);

INSERT INTO tb_pessoa (CELULAR, DATA_NASCIMENTO, EMAIL, NOME, NOME_PREFERENCIA, TELEFONE, ENDERECO_ID) VALUES
('86995913125', DATE '1969-03-30', 'matheus_felipe_daluz@ceuazul.ind.br', 'Matheus Felipe da Luz', null, '8638222020', 2),
('86989576843', DATE '1970-02-17', 'cristiane.sabrina.alves@mectron.com.br', 'Cristiane Sabrina Alves', 'Cris', '8638031235', 2),
('85982827970', DATE '1954-07-04', 'carlos-jesus74@sicredi.com.br', 'Carlos Thomas Jesus', null, '8535878483', 3),
('85999582815', DATE '1956-12-21', 'carla-ramos81@engemed.com', 'Carla Jéssica Ramos', 'Jéssica', '8539263041', 3);
INSERT INTO tb_pessoa_casal (IN_MEMORIAM, PROFISSAO, ID) VALUES
(false, 'Motorista', 1),
(false, 'Professora', 2),
(false, 'Advogado', 3),
(false, 'Contadora', 4);

INSERT INTO tb_pessoa (CELULAR, DATA_NASCIMENTO, EMAIL, NOME, NOME_PREFERENCIA, TELEFONE, ENDERECO_ID) VALUES
('86964745133', DATE '1980-11-30', 'maria@gmail.com', 'Maria Good', 'Maria', '8632145777', 4),
('85988745632', DATE '1959-06-01', 'bruna_pereira_santos_silva@hotmail.com', 'Bruna Pereira Santos Silva', null, '8539263041', 5);
INSERT INTO tb_pessoa_responsavel (GRAU_PARENTESCO, ID) VALUES
('IRMÃ', 5),
('PRIMA', 6);

INSERT INTO tb_casa_retiro (NOME, ENDERECO_ID, RETIRO_ID) values
('Casa de Retiro Mossunguê', 6, null);

INSERT INTO tb_retiro (DATA_INICIO, DATA_FIM, NOME, TEMA, LEMA, CASAL_COORDENADOR_ID, CASA_RETIRO_ID) VALUES
(DATE '2019-12-15', DATE '2019-12-17', '110º Retiro de Casais', 'Como o Pai me amou, eu também te amarei', 'Se vocês obedecerem a meus mandamentos, permanecerão no meu amor (João 15-10)', null, 1),
(DATE '2020-06-15', DATE '2020-06-17', '111º Retiro de Casais', 'Como o Pai me amou, eu também te amarei', 'Se vocês obedecerem a meus mandamentos, permanecerão no meu amor (João 15-10)', null, 1),
(DATE '2022-02-01', DATE '2022-02-03', '112º Retiro de Casais', 'Como o Pai me amou, eu também te amarei', 'Se vocês obedecerem a meus mandamentos, permanecerão no meu amor (João 15-10)', null, 1),
(DATE '2022-07-15', DATE '2022-07-17', '113º Retiro de Casais', 'Como o Pai me amou, eu também te amarei', 'Se vocês obedecerem a meus mandamentos, permanecerão no meu amor (João 15-10)', null, 1);

INSERT INTO tb_casal (DATA_CASAMENTO_CIVIL, DATA_CASAMENTO_RELIGIOSO, OBSERVACOES, ESPOSO_ID, ESPOSA_ID, PADRINHO_ID, RESPONSAVEL_ID, RETIRO_ID) VALUES
(DATE '1999-11-30', DATE '1999-12-01', 'Observacoes se houverem devem ser inseridas nesse campo', 1, 2, null, 5, 1);

INSERT INTO tb_casal (DATA_CASAMENTO_CIVIL, DATA_CASAMENTO_RELIGIOSO, OBSERVACOES, ESPOSO_ID, ESPOSA_ID, PADRINHO_ID, RESPONSAVEL_ID, RETIRO_ID) VALUES
(DATE '2011-01-13', DATE '2020-02-20', 'Observacoes se houverem devem ser inseridas nesse campo', 3, 4, null, 6, 1);

INSERT INTO tb_equipe (NOME_EQUIPE, CASAL_COORDENADOR_ID, RETIRO_ID) VALUES
('Cozinha', 1, 1),
('Copa', 1, 1),
('Boa Ordem', 1, 1),
('Reporter', 1, 1),
('Sineteiro', 1, 1);

INSERT INTO tb_palestra (DATA, TEMA, RETIRO_ID) VALUES
(DATE '2022-07-15', 'Acolhida', null),
(DATE '2022-07-16', 'Sexualidade no Matrimônio', null),
(DATE '2022-07-17', 'Pais e Filhos', null);

INSERT INTO tb_palestrante (NOME, TELEFONE, ENDERECO_ID, PALESTRA_ID) VALUES
('Marcos W. da Fonseca', '41988999943', 7, 1),
('Mirtes T. B. Fonseca', '41987386282', 7, 1),
('Cleusa B. Lopes', '41999712287', 8, 2),
('Silvio Zampar', '41996445540', 9, 3),
('Silvia Zampar', '41996711959', 9, 3);

UPDATE tb_retiro SET CASAL_COORDENADOR_ID = 1, CASA_RETIRO_ID = 1;
UPDATE tb_casa_retiro SET RETIRO_ID = 1;
UPDATE tb_palestra SET RETIRO_ID = 1;
